//A is mostly PS, B is mostly "PT
//three images per trial
// var DataSource = [
// ["c","KITCHEN",3,"y","k1.jpg","b1.jpg","b2.jpg","null","null","null"],
// ["c","KITCHEN",3,"n","b1.jpg","b2.jpg","b3.jpg","null","null","null"],
// ["c","BATHROOM",3,"y","k1.jpg","l1.jpg","b1.jpg","null","null","null"],
// ["c","BATHROOM",6,"y","b1.jpg","l1.jpg","l2.jpg","l3.jpg","l4.jpg","k1.jpg"],
// ["c","BATHROOM",6,"y","b2.jpg","l1.jpg","l2.jpg","l3.jpg","l4.jpg","k1.jpg"],
// ["c","KITCHEN",6,"n","b1.jpg","b2.jpg","b3.jpg","l1.jpg","l2.jpg","l3.jpg"]
// ];

var DataSource = [
["S","KITCHEN",3,"y","Kitchen1.jpg","Bathroom1.jpg","Bathroom2.jpg","null","null","null"],
["S","BATHROOM",3,"y","Bathroom2.jpg","Kitchen2.jpg","Kitchen3.jpg","null","null","null"],
["S","BEACH",3,"y","Beach1.jpg","Forest10.jpg","Forest11.jpg","null","null","null"],
["S","FOREST",3,"y","Forest1.jpg","Beach10.jpg","Beach11.jpg","null","null","null"],
["D","KITCHEN",3,"y","Kitchen4.jpg","Beach2.jpg","Forest2.jpg","null","null","null"],
["D","BATHROOM",3,"y","Bathroom4.jpg","Beach3.jpg","Forest3.jpg","null","null","null"],
["D","BEACH",3,"y","Beach4.jpg","Kitchen5.jpg","Bathroom5.jpg","null","null","null"],
["D","FOREST",3,"y","Forest4.jpg","Kitchen6.jpg","Bathroom6.jpg","null","null","null"],
["S","KITCHEN",3,"n","Bathroom7.jpg","Bathroom8.jpg","Bathroom9.jpg","null","null","null"],
["S","BATHROOM",3,"n","Kitchen7.jpg","Kitchen8.jpg","Kitchen9.jpg","null","null","null"],
["S","BEACH",3,"n","Forest12.jpg","Forest13.jpg","Forest14.jpg","null","null","null"],
["S","FOREST",3,"n","Beach12.jpg","Beach13.jpg","Beach14.jpg","null","null","null"],
["D","KITCHEN",3,"n","Forest5.jpg","Beach5.jpg","Beach6.jpg","null","null","null"],
["D","BATHROOM",3,"n","Beach7.jpg","Forest6.jpg","Forest7.jpg","null","null","null"],
["D","BEACH",3,"n","Kitchen17.jpg","Bathroom17.jpg","Bathroom18.jpg","null","null","null"],
["D","FOREST",3,"n","Kitchen18.jpg","Kitchen19.jpg","Bathroom19.jpg","null","null","null"],
["S","KITCHEN",6,"y","Kitchen10.jpg","Bathroom11.jpg","Bathroom12.jpg","Bathroom13.jpg","Bathroom14.jpg","Bathroom15.jpg"],
["S","BATHROOM",6,"y","Bathroom10.jpg","Kitchen11.jpg","Kitchen12.jpg","Kitchen13.jpg","Kitchen14.jpg","Kitchen15.jpg"],
["S","BEACH",6,"y","Beach8.jpg","Forest15.jpg","Forest16.jpg","Forest17.jpg","Forest18.jpg","Forest19.jpg"],
["S","FOREST",6,"y","Forest8.jpg","Beach15.jpg","Beach16.jpg","Beach17.jpg","Beach18.jpg","Beach19.jpg"],
["D","KITCHEN",6,"y","Kitchen16.jpg","Beach20.jpg","Beach1.jpg","Beach2.jpg","Forest2.jpg","Forest3.jpg"],
["D","BATHROOM",6,"y","Bathroom16.jpg","Forest20.jpg","Forest1.jpg","Forest4.jpg","Beach3.jpg","Beach4.jpg"],
["D","BEACH",6,"y","Beach9.jpg","Kitchen6.jpg","Kitchen7.jpg","Kitchen8.jpg","Bathroom6.jpg","Bathroom7.jpg"],
["D","FOREST",6,"y","Forest9.jpg","Kitchen9.jpg","Kitchen10.jpg","Bathroom8.jpg","Bathroom9.jpg","Bathroom10.jpg"],
["S","KITCHEN",6,"n","Bathroom20.jpg","Bathroom1.jpg","Bathroom2.jpg","Bathroom3.jpg","Bathroom4.jpg","Bathroom5.jpg"],
["S","BATHROOM",6,"n","Kitchen20.jpg","Kitchen1.jpg","Kitchen2.jpg","Kitchen3.jpg","Kitchen4.jpg","Kitchen5.jpg"],
["S","BEACH",6,"n","Forest5.jpg","Forest6.jpg","Forest7.jpg","Forest8.jpg","Forest9.jpg","Forest10.jpg"],
["S","FOREST",6,"n","Beach5.jpg","Beach6.jpg","Beach7.jpg","Beach8.jpg","Beach9.jpg","Beach10.jpg"],
["D","KITCHEN",6,"n","Beach11.jpg","Beach15.jpg","Beach13.jpg","Forest11.jpg","Forest13.jpg","Forest15.jpg"],
["D","BATHROOM",6,"n","Beach12.jpg","Beach16.jpg","Beach14.jpg","Forest12.jpg","Forest16.jpg","Forest14.jpg"],
["D","BEACH",6,"n","Kitchen7.jpg","Kitchen10.jpg","Kitchen13.jpg","Bathroom8.jpg","Bathroom11.jpg","Bathroom14.jpg"],
["D","FOREST",6,"n","Kitchen8.jpg","Kitchen11.jpg","Kitchen14.jpg","Bathroom7.jpg","Bathroom10.jpg","Bathroom13.jpg"],
["S","KITCHEN",3,"y","Kitchen11.jpg","Bathroom1.jpg","Bathroom10.jpg","null","null","null"],
["S","BATHROOM",3,"y","Bathroom11.jpg","Kitchen1.jpg","Kitchen10.jpg","null","null","null"],
["S","BEACH",3,"y","Beach17.jpg","Forest2.jpg","Forest8.jpg","null","null","null"],
["S","FOREST",3,"y","Forest17.jpg","Beach2.jpg","Beach18.jpg","null","null","null"],
["D","KITCHEN",3,"y","Kitchen14.jpg","Forest20.jpg","Beach6.jpg","null","null","null"],
["D","BATHROOM",3,"y","Bathroom14.jpg","Beach20.jpg","Forest6.jpg","null","null","null"],
["D","BEACH",3,"y","Beach3.jpg","Kitchen7.jpg","Bathroom18.jpg","null","null","null"],
["D","FOREST",3,"y","Forest3.jpg","Bathroom7.jpg","Kitchen18.jpg","null","null","null"],
["S","KITCHEN",3,"n","Bathroom13.jpg","Bathroom18.jpg","Bathroom4.jpg","null","null","null"],
["S","BATHROOM",3,"n","Kitchen13.jpg","Kitchen18.jpg","Kitchen4.jpg","null","null","null"],
["S","BEACH",3,"n","Forest4.jpg","Forest9.jpg","Forest14.jpg","null","null","null"],
["S","FOREST",3,"n","Beach4.jpg","Beach9.jpg","Beach14.jpg","null","null","null"],
["D","KITCHEN",3,"n","Beach6.jpg","Beach9.jpg","Forest1.jpg","null","null","null"],
["D","BATHROOM",3,"n","Forest6.jpg","Forest9.jpg","Beach1.jpg","null","null","null"],
["D","BEACH",3,"n","Kitchen5.jpg","Kitchen16.jpg","Bathroom20.jpg","null","null","null"],
["D","FOREST",3,"n","Bathroom5.jpg","Bathroom16.jpg","Kitchen20.jpg","null","null","null"],
["S","KITCHEN",6,"y","Kitchen9.jpg","Bathroom2.jpg","Bathroom4.jpg","Bathroom6.jpg","Bathroom8.jpg","Bathroom14.jpg"],
["S","BATHROOM",6,"y","Bathroom9.jpg","Kitchen2.jpg","Kitchen4.jpg","Kitchen6.jpg","Kitchen8.jpg","Kitchen10.jpg"],
["S","BEACH",6,"y","Beach16.jpg","Forest2.jpg","Forest4.jpg","Forest6.jpg","Forest8.jpg","Forest10.jpg"],
["S","FOREST",6,"y","Forest16.jpg","Beach2.jpg","Beach4.jpg","Beach6.jpg","Beach8.jpg","Beach10.jpg"],
["D","KITCHEN",6,"y","Kitchen10.jpg","Beach1.jpg","Beach5.jpg","Forest3.jpg","Forest7.jpg","Forest9.jpg"],
["D","BATHROOM",6,"y","Bathroom10.jpg","Forest1.jpg","Forest5.jpg","Beach3.jpg","Beach7.jpg","Beach9.jpg"],
["D","BEACH",6,"y","Beach18.jpg","Kitchen1.jpg","Kitchen3.jpg","Kitchen5.jpg","Bathroom7.jpg","Bathroom9.jpg"],
["D","FOREST",6,"y","Forest18.jpg","Bathroom1.jpg","Bathroom3.jpg","Bathroom5.jpg","Kitchen7.jpg","Kitchen9.jpg"],
["S","KITCHEN",6,"n","Bathroom11.jpg","Bathroom13.jpg","Bathroom15.jpg","Bathroom17.jpg","Bathroom19.jpg","Bathroom2.jpg"],
["S","BATHROOM",6,"n","Kitchen11.jpg","Kitchen13.jpg","Kitchen15.jpg","Kitchen17.jpg","Kitchen19.jpg","Kitchen2.jpg"],
["S","BEACH",6,"n","Forest14.jpg","Forest16.jpg","Forest18.jpg","Forest20.jpg","Forest2.jpg","Forest4.jpg"],
["S","FOREST",6,"n","Beach14.jpg","Beach16.jpg","Beach18.jpg","Beach20.jpg","Beach2.jpg","Beach4.jpg"],
["D","KITCHEN",6,"n","Beach13.jpg","Beach15.jpg","Beach17.jpg","Forest9.jpg","Forest11.jpg","Forest13.jpg"],
["D","BATHROOM",6,"n","Forest13.jpg","Forest15.jpg","Forest17.jpg","Beach9.jpg","Beach11.jpg","Beach13.jpg"],
["D","BEACH",6,"n","Kitchen3.jpg","Kitchen4.jpg","Kitchen5.jpg","Bathroom4.jpg","Bathroom5.jpg","Bathroom6.jpg"],
["D","FOREST",6,"n","Bathroom3.jpg","Bathroom4.jpg","Bathroom5.jpg","Kitchen4.jpg","Kitchen5.jpg","Kitchen6.jpg"],
["S","KITCHEN",3,"y","Kitchen19.jpg","Bathroom11.jpg","Bathroom15.jpg","null","null","null"],
["S","BATHROOM",3,"y","Bathroom19.jpg","Kitchen11.jpg","Kitchen15.jpg","null","null","null"],
["S","BEACH",3,"y","Beach3.jpg","Forest8.jpg","Forest10.jpg","null","null","null"],
["S","FOREST",3,"y","Forest3.jpg","Beach8.jpg","Beach10.jpg","null","null","null"],
["D","KITCHEN",3,"y","Kitchen6.jpg","Forest12.jpg","Beach19.jpg","null","null","null"],
["D","BATHROOM",3,"y","Bathroom6.jpg","Beach17.jpg","Forest19.jpg","null","null","null"],
["D","BEACH",3,"y","Beach6.jpg","Kitchen6.jpg","Bathroom17.jpg","null","null","null"],
["D","FOREST",3,"y","Forest6.jpg","Bathroom6.jpg","Kitchen17.jpg","null","null","null"],
["S","KITCHEN",3,"n","Bathroom13.jpg","Bathroom3.jpg","Bathroom20.jpg","null","null","null"],
["S","BATHROOM",3,"n","Kitchen13.jpg","Kitchen8.jpg","Kitchen20.jpg","null","null","null"],
["S","BEACH",3,"n","Forest1.jpg","Forest10.jpg","Forest18.jpg","null","null","null"],
["S","FOREST",3,"n","Beach1.jpg","Beach10.jpg","Beach18.jpg","null","null","null"],
["D","KITCHEN",3,"n","Forest12.jpg","Beach15.jpg","Beach19.jpg","null","null","null"],
["D","BATHROOM",3,"n","Beach11.jpg","Beach12.jpg","Forest19.jpg","null","null","null"],
["D","BEACH",3,"n","Kitchen12.jpg","Bathroom8.jpg","Bathroom12.jpg","null","null","null"],
["D","FOREST",3,"n","Bathroom14.jpg","Kitchen16.jpg","Kitchen1.jpg","null","null","null"],
["S","KITCHEN",6,"y","Kitchen3.jpg","Bathroom12.jpg","Bathroom14.jpg","Bathroom18.jpg","Bathroom19.jpg","Bathroom16.jpg"],
["S","BATHROOM",6,"y","Bathroom3.jpg","Kitchen12.jpg","Kitchen16.jpg","Kitchen14.jpg","Kitchen8.jpg","Kitchen20.jpg"],
["S","BEACH",6,"y","Beach2.jpg","Forest20.jpg","Forest7.jpg","Forest5.jpg","Forest13.jpg","Forest19.jpg"],
["S","FOREST",6,"y","Forest2.jpg","Beach17.jpg","Beach7.jpg","Beach8.jpg","Beach16.jpg","Beach20.jpg"],
["D","KITCHEN",6,"y","Kitchen2.jpg","Forest18.jpg","Forest11.jpg","Beach19.jpg","Beach12.jpg","Beach11.jpg"],
["D","BATHROOM",6,"y","Bathroom1.jpg","Forest12.jpg","Forest15.jpg","Forest16.jpg","Beach5.jpg","Beach15.jpg"],
["D","BEACH",6,"y","Beach20.jpg","Kitchen12.jpg","Kitchen16.jpg","Kitchen19.jpg","Bathroom20.jpg","Bathroom18.jpg"],
["D","FOREST",6,"y","Forest20.jpg","Kitchen20.jpg","Kitchen9.jpg","Bathroom16.jpg","Bathroom12.jpg","Bathroom17.jpg"],
["S","KITCHEN",6,"n","Bathroom15.jpg","Bathroom19.jpg","Bathroom1.jpg","Bathroom3.jpg","Bathroom10.jpg","Bathroom11.jpg"],
["S","BATHROOM",6,"n","Kitchen11.jpg","Kitchen14.jpg","Kitchen15.jpg","Kitchen18.jpg","Kitchen17.jpg","Kitchen13.jpg"],
["S","BEACH",6,"n","Forest14.jpg","Forest11.jpg","Forest3.jpg","Forest7.jpg","Forest20.jpg","Forest18.jpg"],
["S","FOREST",6,"n","Beach17.jpg","Beach15.jpg","Beach1.jpg","Beach7.jpg","Beach16.jpg","Beach4.jpg"],
["D","KITCHEN",6,"n","Forest5.jpg","Forest12.jpg","Forest11.jpg","Beach12.jpg","Beach19.jpg","Beach7.jpg"],
["D","BATHROOM",6,"n","Beach5.jpg","Beach13.jpg","Beach14.jpg","Forest7.jpg","Forest19.jpg","Forest15.jpg"],
["D","BEACH",6,"n","Kitchen12.jpg","Kitchen14.jpg","Kitchen17.jpg","Bathroom12.jpg","Bathroom20.jpg","Bathroom17.jpg"],
["D","FOREST",6,"n","Kitchen18.jpg","Kitchen19.jpg","Kitchen15.jpg","Bathroom15.jpg","Bathroom16.jpg","Bathroom9.jpg"]
];