
var DataSourceA = [
["A",1,"1_NOTARGET.png","."],
["A",1,"1_BOTTOMRIGHT.png","R"],
["A",1,"1_BOTTOMLEFT_F.png","FR"],
["A",2,"2_NOTARGET.png","."],
["A",2,"2_TOPLEFT.png","L"],
["A",2,"2_BOTTOMRIGHT.png","R"],
["A",3,"3_NOTARGET.png","."],
["A",3,"3_RIGHTCLOSE.png","R"],
["A",3,"3_RIGHTFAR.png","R"],
["A",4,"4_NOTARGET.png","."],
["A",4,"4_FARRIGHT.png","R"],
["A",5,"5_NOTARGET.png","."],
["A",5,"5_FARRIGHT.png","R"],
["A",6,"6_NOTARGET.png","."],
["A",6,"6_RIGHT.png","R"],
["A",7,"7_NOTARGET.png","."],
["A",7,"7_LEFT.png","L"],
["A",8,"8_NOTARGET.png","."],
["A",8,"8_RIGHT.png","R"],
["A",9,"9_NOTARGET.png","."],
["A",9,"9_RIGHT.png","R"],
["A",10,"10_LEFT.png","L"],
["A",10,"10_NOTARGET_F.png","."],
["A",10,"10_RIGHT_F.png","FL"],
["A",11,"11_LEFT.png","L"],
["A",11,"11_NOTARGET_F.png","."],
["A",11,"11_RIGHT_F.png","FL"],
["A",12,"12_LEFT.png","L"],
["A",12,"12_NOTARGET_F.png","."],
["A",12,"12_RIGHT_F.png","FL"],
["A",13,"13_LEFT.png","L"],
["A",13,"13_NOTARGET_F.png","."],
["A",13,"13_RIGHT_F.png","FL"],
["A",14,"14_NOTARGET_F.png","."],
["A",14,"14_RIGHT_F.png","FL"],
["A",14,"14_LEFT_F.png","FR"],
["A",15,"15_NOTARGET_F.png","."],
["A",15,"15_RIGHT_F.png","FL"],
["A",15,"15_LEFT_F.png","FR"],
["A",16,"16_NOTARGET_F.png","."],
["A",16,"16_RIGHT_F.png","FL"],
["A",16,"16_LEFT_F.png","FR"],
["A",17,"17_NOTARGET_F.png","."],
["A",17,"17_CLOSERIGHT_F.png","FL"],
["A",17,"17_FARRIGHT_F.png","FL"],
["A",17,"17_CLOSELEFT_F.png","FR"],
["A",17,"17_FARLEFT_F.png","FR"],
["A",18,"18_NOTARGET_F.png","."],
["A",18,"18_RIGHT_F.png","FL"],
["A",18,"18_LEFT_F.png","FR"]
];

// var DataSourceB = [
// ["B",1,"Gabby3.jpg","right"],
// ["B",2,"Gabby4.jpg","right"]
// ];

var DataSourceB = [
["B",1,"1_BOTTOMLEFT.png","L"],
["B",1,"1_NOTARGET_F.png","."],
["B",1,"1_BOTTOMRIGHT_F.png","FL"],
["B",2,"2_NOTARGET_F.png","."],
["B",2,"2_BOTTOMRIGHT_F.png","FL"],
["B",2,"2_TOPLEFT_F.png","FR"],
["B",3,"3_NOTARGET_F.png","."],
["B",3,"3_RIGHTCLOSE_F.png","FL"],
["B",3,"3_RIGHTFAR_F.png","FL"],
["B",4,"4_NOTARGET_F.png","."],
["B",4,"4_FARRIGHT_F.png","FL"],
["B",5,"5_NOTARGET_F.png","."],
["B",5,"5_FARRIGHT_F.png","FL"],
["B",6,"6_NOTARGET_F.png","."],
["B",6,"6_RIGHT_F.png","FL"],
["B",7,"7_NOTARGET_F.png","."],
["B",7,"7_LEFT_F.png","FR"],
["B",8,"8_NOTARGET_F.png","."],
["B",8,"8_RIGHT_F.png","FL"],
["B",9,"9_NOTARGET_F.png","."],
["B",9,"9_RIGHT_F.png","FL"],
["B",10,"10_NOTARGET.png","."],
["B",10,"10_RIGHT.png","R"],
["B",10,"10_LEFT_F.png","FR"],
["B",11,"11_NOTARGET.png","."],
["B",11,"11_RIGHT.png","R"],
["B",11,"11_LEFT_F.png","FR"],
["B",12,"12_NOTARGET.png","."],
["B",12,"12_RIGHT.png","R"],
["B",12,"12_LEFT_F.png","FR"],
["B",13,"13_NOTARGET.png","."],
["B",13,"13_RIGHT.png","R"],
["B",13,"13_LEFT_F.png","FR"],
["B",14,"14_NOTARGET.png","."],
["B",14,"14_LEFT.png","L"],
["B",14,"14_RIGHT.png","R"],
["B",15,"15_NOTARGET.png","."],
["B",15,"15_LEFT.png","L"],
["B",15,"15_RIGHT.png","R"],
["B",16,"16_NOTARGET.png","."],
["B",16,"16_LEFT.png","L"],
["B",16,"16_RIGHT.png","R"],
["B",17,"17_NOTARGET.png","."],
["B",17,"17_CLOSELEFT.png","L"],
["B",17,"17_FARLEFT.png","L"],
["B",17,"17_CLOSERIGHT.png","R"],
["B",17,"17_FARRIGHT.png","R"],
["B",18,"18_NOTARGET.png","."],
["B",18,"18_LEFT.png","L"],
["B",18,"18_RIGHT.png","R"]
];

var AllDataSources=[DataSourceA,DataSourceB];